version: "3.8"
services:
  postgres:
    container_name: ecommerce-training-postgres-dev
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    networks:
      - postgres

networks:
    postgres:
        external: true
